Running cluster for deep fits
216331 216343 normal
Running object 216331
Not enough g observations!
Min gap is: 19.9375
Number of observations now:  7
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  23
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  66
Counts: {'r': 7, 'i': 23, 'z': 64}
Mu: {'g': 0.0, 'r': 0.11174012, 'i': 0.20165008, 'z': 0.38457435}
No handles with labels found to put in legend.
No handles with labels found to put in legend.
ClusterEmcee2_linear_mu_all_and_single_fast.py:779: RuntimeWarning: invalid value encountered in sqrt
  slope_err = [np.sqrt(res_g[0][0]), 0, np.sqrt(res_i[0][0]), np.sqrt(res_z[0][0])]
ClusterEmcee2_linear_mu_all_and_single_fast.py:780: RuntimeWarning: invalid value encountered in sqrt
  int_err = [np.sqrt(res_g[1][1]), 0, np.sqrt(res_i[1][1]), np.sqrt(res_z[1][1])]
Variable??
0
0
Non-Variable source in g
Variable??
0.02377759675008758
3.673881845807813
Variable Source in r!!
Variable??
0.02954816594785419
1.0266190476386898
Non-Variable source in i
Variable??
0.06208034232258797
1.352479432076029
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 591.2921930826906]
Slope Error: [0.0, 0, 0.0, nan]
intercepts:  [0, 0, 0, 71.77636488859143]
Int Error:   [0.0, 0, 0.0, nan]
StDev:       [0.0, 0.135017, 0.047711197, 0.10745647]
Spread:      0/4
Spread values: 
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 873, in <module>
    perform_emcee_step2(time, flux_mod, err_mod**2, dMu_dict, scale_dict, color_sort_ones, ROW, mu, var_count)
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 614, in perform_emcee_step2
    sampler.run_mcmc(pos, 200)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 456, in compute_log_prob
    raise ValueError("Probability function returned NaN")
ValueError: Probability function returned NaN
srun: error: ccc0242: task 0: Exited with exit code 1
