Running cluster for deep fits
21751 21752 normal
Running object 21751
Min gap is: 643.1758
Min gap is: 0.00390625
New time_gap is :0.00790625
Min gap is: 0.00390625
New time_gap is :0.00790625
Counts: {'r': 3, 'i': 13, 'z': 67}
Mu: {'g': 0.0, 'r': 0.10792926, 'i': 0.16085449, 'z': 0.35098043}
No handles with labels found to put in legend.
No handles with labels found to put in legend.
ClusterEmcee2_linear_mu_all_and_single_fast.py:774: RuntimeWarning: invalid value encountered in sqrt
  slope_err = [np.sqrt(res_g[0][0]), 0, np.sqrt(res_i[0][0]), np.sqrt(res_z[0][0])]
ClusterEmcee2_linear_mu_all_and_single_fast.py:775: RuntimeWarning: invalid value encountered in sqrt
  int_err = [np.sqrt(res_g[1][1]), 0, np.sqrt(res_i[1][1]), np.sqrt(res_z[1][1])]
Variable??
0
0
Non-Variable source in g
Variable??
0.029168344840513425
4.85840278749896
Variable Source in r!!
Variable??
0.030523333569027648
0.8487272179371547
Non-Variable source in i
Variable??
0.06914569848758277
2.21216099267675
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 2403.0841277737345]
Slope Error: [0.0, 0, 0.0, nan]
intercepts:  [0, 0, 0, 184.89921150474032]
Int Error:   [0.0, 0, 0.0, nan]
StDev:       [0.15033942, 0.13932417, 0.037763655, 0.110800445]
Spread:      0/4
Spread values: 
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 858, in <module>
    perform_emcee_step2(time, flux_mod, err_mod**2, dMu_dict, scale_dict, color_sort_ones, ROW, mu, var_count)
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 609, in perform_emcee_step2
    sampler.run_mcmc(pos, 200)
  File "/home/thrush2/scratch/mypython3/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/thrush2/scratch/mypython3/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/thrush2/scratch/mypython3/emcee/ensemble.py", line 456, in compute_log_prob
    raise ValueError("Probability function returned NaN")
ValueError: Probability function returned NaN
srun: error: ccc0240: task 0: Exited with exit code 1
