Running cluster for deep fits
59074 59075 normal
Running object 59074
Min gap is: 0.00390625
New time_gap is :0.00790625
Min gap is: 0.00390625
New time_gap is :0.00790625
Min gap is: 0.00390625
New time_gap is :0.00790625
Counts: {'r': 3, 'i': 87, 'z': 148}
Mu: {'g': 0.0, 'r': 0.22217521, 'i': 0.22167897, 'z': 0.4123348}
No handles with labels found to put in legend.
No handles with labels found to put in legend.
/usr/local/python/3.7.0/lib/python3.7/site-packages/scipy/optimize/minpack.py:794: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
Variable??
0
0
Non-Variable source in g
Variable??
0.021979949377497043
43.67216874488303
Variable Source in r!!
Variable??
0.025737507715693803
2.0311481329569285
Non-Variable source in i
Variable??
0.050415401745377494
2.6179192457678457
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 1]
Slope Error: [0.0, 0, 0.0, inf]
intercepts:  [0, 0, 0, 104.23693264195981]
Int Error:   [0.0, 0, 0.0, inf]
StDev:       [0.0, 0.16185606, 0.04801969, 0.08848233]
Spread:      0/4
Spread values: 
ClusterEmcee2_linear_mu_all_and_single_fast.py:855: RuntimeWarning: invalid value encountered in multiply
  err_mod += np.sqrt(err**2 + dMu_dict_err[color]**2 + (flux-dMu_dict[color])**2/scale_dict[color]**2 * scale_err[color]**2)/scale_dict[color]*color_sort_ones[color_dict[color]]
ClusterEmcee2_linear_mu_all_and_single_fast.py:220: RuntimeWarning: invalid value encountered in double_scalars
  lp_app = lp + lnlike_fast_linear.lnlike(theta, x, y, yerr)
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 858, in <module>
    perform_emcee_step2(time, flux_mod, err_mod**2, dMu_dict, scale_dict, color_sort_ones, ROW, mu, var_count)
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 609, in perform_emcee_step2
    sampler.run_mcmc(pos, 200)
  File "/home/thrush2/scratch/mypython3/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/thrush2/scratch/mypython3/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/thrush2/scratch/mypython3/emcee/ensemble.py", line 456, in compute_log_prob
    raise ValueError("Probability function returned NaN")
ValueError: Probability function returned NaN
srun: error: ccc0240: task 0: Exited with exit code 1
