Running cluster for deep fits
70593 71000 normal
Running object 70593
Not enough g observations!
Min gap is: 52.98047
Number of observations now:  5
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  33
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  43
Counts: {'r': 5, 'i': 33, 'z': 42}
Mu: {'g': 0.0, 'r': 0.31695688, 'i': 0.2423811, 'z': 0.3759652}
No handles with labels found to put in legend.
No handles with labels found to put in legend.
/usr/local/python/3.7.0/lib/python3.7/site-packages/scipy/optimize/minpack.py:794: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
Variable??
0
0
Non-Variable source in g
Variable??
0.04513371865639497
22.839740173033526
Variable Source in r!!
Variable??
0.0415177162180349
1.2391517304613051
Non-Variable source in i
Variable??
0.0688157960582174
3.221522710462832
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 1]
Slope Error: [0.0, 0, 0.0, inf]
intercepts:  [0, 0, 0, -80.88060702045057]
Int Error:   [0.0, 0, 0.0, inf]
StDev:       [0.0, 0.15910824, 0.23051172, 0.08154338]
Spread:      0/4
Spread values: 
ClusterEmcee2_linear_mu_all_and_single_fast.py:870: RuntimeWarning: invalid value encountered in multiply
  err_mod += np.sqrt(err**2 + dMu_dict_err[color]**2 + (flux-dMu_dict[color])**2/scale_dict[color]**2 * scale_err[color]**2)/scale_dict[color]*color_sort_ones[color_dict[color]]
ClusterEmcee2_linear_mu_all_and_single_fast.py:225: RuntimeWarning: invalid value encountered in double_scalars
  lp_app = lp + lnlike_fast_linear.lnlike(theta, x, y, yerr)
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 873, in <module>
    perform_emcee_step2(time, flux_mod, err_mod**2, dMu_dict, scale_dict, color_sort_ones, ROW, mu, var_count)
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 614, in perform_emcee_step2
    sampler.run_mcmc(pos, 200)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 456, in compute_log_prob
    raise ValueError("Probability function returned NaN")
ValueError: Probability function returned NaN
srun: error: ccc0242: task 0: Exited with exit code 1
