Running cluster for deep fits
205398 205399 normal
Running object 205398
Not enough g observations!
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  6
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  39
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  104
Counts: {'r': 6, 'i': 37, 'z': 97}
Mu: {'g': 0.0, 'r': 0.18702827, 'i': 0.26304722, 'z': 0.4183355}
No handles with labels found to put in legend.
No handles with labels found to put in legend.
ClusterEmcee2_linear_mu_all_and_single_fast.py:779: RuntimeWarning: invalid value encountered in sqrt
  slope_err = [np.sqrt(res_g[0][0]), 0, np.sqrt(res_i[0][0]), np.sqrt(res_z[0][0])]
ClusterEmcee2_linear_mu_all_and_single_fast.py:780: RuntimeWarning: invalid value encountered in sqrt
  int_err = [np.sqrt(res_g[1][1]), 0, np.sqrt(res_i[1][1]), np.sqrt(res_z[1][1])]
Variable??
0
0
Non-Variable source in g
Variable??
0.03724420767226005
13.348118285397092
Variable Source in r!!
Variable??
0.04855587787506321
1.3090997123869803
Non-Variable source in i
Variable??
0.06816220516097421
2.592165561838934
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 2.0]
Slope Error: [0.0, 0, 0.0, nan]
intercepts:  [0, 0, 0, -0.19329156045258]
Int Error:   [0.0, 0, 0.0, nan]
StDev:       [0.123115435, 0.136047, 0.06627441, 0.20284341]
Spread:      0/4
Spread values: 
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 873, in <module>
    perform_emcee_step2(time, flux_mod, err_mod**2, dMu_dict, scale_dict, color_sort_ones, ROW, mu, var_count)
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 614, in perform_emcee_step2
    sampler.run_mcmc(pos, 200)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 456, in compute_log_prob
    raise ValueError("Probability function returned NaN")
ValueError: Probability function returned NaN
srun: error: ccc0249: task 0: Exited with exit code 1
