Running cluster for deep fits
200570 200571 normal
Running object 200570
Min gap is: 3.8945312
Min gap is: 0.00390625
New time_gap is :0.00790625
Min gap is: 0.00390625
New time_gap is :0.00790625
Min gap is: 0.00390625
New time_gap is :0.00790625
Counts: {'g': 7, 'r': 28, 'i': 22, 'z': 8}
Mu: {'g': 0.15837853, 'r': 0.17630889, 'i': 0.25136226, 'z': 0.3824218}
/usr/local/python/3.7.0/lib/python3.7/site-packages/scipy/optimize/minpack.py:794: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
Variable??
0.032465115152028434
1.2481963970505563
Non-Variable source in g
Variable??
0.025653732694709053
3.1945963010444594
Variable Source in r!!
Variable??
0.03856237807620502
2.23415627181788
Non-Variable source in i
Variable??
0.07588678632150951
0.5600060874857775
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 1]
Slope Error: [1.2316331740502033, 0, 0.23595582127937917, inf]
intercepts:  [-0.11567100622441928, 0, -0.11664632591935824, 0.5324189661092542]
Int Error:   [0.17000602433545567, 0, 0.06932361628102114, inf]
StDev:       [0.030863678, 0.14811201, 0.0899403, 0.07680702]
Spread:      0/4
Spread values: 
ClusterEmcee2_linear_mu_all_and_single_fast.py:865: RuntimeWarning: invalid value encountered in multiply
  err_mod += np.sqrt(err**2 + dMu_dict_err[color]**2 + (flux-dMu_dict[color])**2/scale_dict[color]**2 * scale_err[color]**2)/scale_dict[color]*color_sort_ones[color_dict[color]]
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 868, in <module>
    perform_emcee_step2(time, flux_mod, err_mod**2, dMu_dict, scale_dict, color_sort_ones, ROW, mu, var_count)
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 609, in perform_emcee_step2
    sampler.run_mcmc(pos, 200)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 456, in compute_log_prob
    raise ValueError("Probability function returned NaN")
ValueError: Probability function returned NaN
srun: error: ccc0241: task 0: Exited with exit code 1
